### ISSUE TITLE
Lights show read only in Homeassistant

### ISSUE THREAD

**Issue by KrickGregory** [shamanenas/has_domintell#10]
Thanks for the good effort for making this add-on.
I did everything from readme file and after long time I succeeded in showing my lights in homeassistant. 
BUT : they are all read only. So I can't switch or dim them. I can, but after 2 seconds the swicht in HA goes back. HA says it has no unique id and because of that you can't change settings. But that's normal if you add something through config file. So it must be something else.

Any idea what problem could be for this?

PS : the configuration.yaml file is very, very difficult to get right with the spaces. I only could solve it with a yaml validation file on the internet. 

Thanks.

**Comment by KrickGregory** [comment]
For those who mess with it too. It's normal that the lights are read only because they are made in config file and that's what the read only means.
I got it working by removing my password from the deth02 module. 
Now I still have 2 problems.
I have to restart homeassistant few times to take control of what is on and of and switch them
I can't get it working with my password. Do I need to put "" around it?
I can't get scenes from domintell working. Don't think it's possible.

Thanks.

**Comment by soliveira** [comment]
> BUT : they are all read only.

Hi there I have a custom version working on my setup all the lights work perfectly. 

Would you share a portion of the config to check if it’s a configuration issue. Also look at the log. There might be useful information.

**Comment by soliveira** [comment]
> I have to restart homeassistant few times to take control of what is on and of and switch them

There is an issue with this version: the domintell allows only 2 open sessions simultaneously. So if you open the domintell app twice or in two different devices HA will lose the connection and won’t connect again. 

I have created a fork that solves this issue but it’s only tested on deth04. 

As for scenes I’ve never experienced any issue. It is working on my end.

**Comment by KrickGregory** [comment]
Got it up and working. Had some mistakes in my config.

Thanks.
