### ISSUE TITLE
Coming problems in 2025.1 update of home assistant

### ISSUE THREAD

**Issue by KrickGregory** [shamanenas/has_domintell#17]
Hey,

seems we will have problems in 2025. Is there some update planned for this? Or should we not update anymore?

Problem 1:
Entity None (<class 'custom_components.domintell.climate.DomintellClimateDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|PRESET_MODE: 17>, please report it to the author of the 'domintell' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Problem 2:
Entity None (<class 'custom_components.domintell.climate.DomintellClimateDevice'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'domintell' custom integration

Problem 3:
Entity light.duplex_dimmer (<class 'custom_components.domintell.light.DomintellDimmerLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 1> and color modes, please report it to the author of the 'domintell' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Problem 4: 
light.led_licht_vergeten (<class 'custom_components.domintell.light.DomintellLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'domintell' custom integration

Problem 5:
TEMP_CELSIUS was used from domintell, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'domintell' custom integration

Thanks for having a look at it and let us know if we should stop updating if we want to keep Domintell.

Grt Gregory

**Comment by zilvinasbin** [comment]
Hi,
Thanks for the message. Pretty busy with my projects right now. I will try to find some time to update the driver in the second half of December. I an using it myself so I realy want to support upcoming HA in 2025.

**Comment by KrickGregory** [comment]
You made my day with your message.  Thanks. Have a nice day.

**Comment by zilvinasbin** [comment]
Hi @KrickGregory !
769c2fd shall have  the issue fixed, 
I am using it now with HA 2024.12

**Comment by zilvinasbin** [comment]
Re-open if needed

**Comment by KrickGregory** [comment]
Dear,

Thank you for your efforts. And indeed. Lights and dimmers don't have problems anymore with your update. But for my leds with Modules DLED I still get errors that color mode is not used. And I'm sorry but do you have plans to update the climate.py too? I tried to change that by myself with help of chatgpt but I can't seem to get it working without errors.

**Comment by zilvinasbin** [comment]
@KrickGregory Climate.py was also updated in the master branch. Let me know if does not work. 

I don't know which component you are using for LEDS. Can you post errors here?

**Comment by KrickGregory** [comment]
It works. Except for the color mode of my lights en espacialy the DLED01, 4 (signaling) LEDs Module. Logfile from five minutes ago after restart and updated py files of you.

[home-assistant_2024-12-10T19-41-38.786Z.log](https://github.com/user-attachments/files/18085070/home-assistant_2024-12-10T19-41-38.786Z.log)

And I realy apreciate your time. 


Grt Gregory

**Comment by yigitar** [comment]
Hello,

1) The warning is still active.

Log details (WARNING)
Logger: homeassistant.components.light
Source: components/light/__init__.py:1353
integration: Light (documentation, issues)
First occurred: 20:14:48 (16 occurrences)
Last logged: 20:14:48

light.lamba_mutfak (<class 'custom_components.domintell 222.light.DomintellLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'domintell' custom integration

2) I can't make trv module work. some outputs work just as bir modules. But neither UI identifies them up and down, nor the channel 5+ work. 

3) I can't define area definition to devices, so in zone pages none of domintell devices shows.

4) İn entity page there are warnings like this: This entity ('light.lamba_yatak_odasi_puf') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.
