### ISSUE TITLE
Support for TRV modules

### ISSUE THREAD

**Issue by dnouls** [shamanenas/has_domintell#4]
It would be nice to add support for more module types. I have some TRV modules used to control my screens. I could automate them based on wind and sun conditions.

**Comment by zilvinasbin** [comment]
I have no TRV modules in my installation. If you are interested and have some python knowledge I can assist on developing this part by yourself.

**Comment by dnouls** [comment]
I saw somebody else created a pull request for cover support and it seems there is already support in the python library as well. I am a developer, but not Python, but always eager to learn new things.

**Comment by zilvinasbin** [comment]
Yep, I approved the pull request.  The code looks ok. Would be great if you can test the cover support.

**Comment by dnouls** [comment]
Now I need to figure out how to setup my home assistant to use this new cover functionality. (there is no documentation).
I tried to configure a cover like I define lights, but that does not seem to work. (here I am trying to register the TRV model.channel to control one of my shades.

```
cover:
  - platform: domintell
    devices:
      - type: TRV
        module: 239b
        channel: 3
        name: Screen Zolder
```
When I try to access it in Homekit I get an error:
Failed to call service cover/open_cover. 'DTRV01Module' object has no attribute 'open_cover'

I guess this is not how I am supposed to control a cover ?

**Comment by zilvinasbin** [comment]
haven't tested it yet.

**Comment by dnouls** [comment]
OK, it works with the latest release. If did find a small glitch in that the initial state of a cover is always "closed".
